### ISSUE TITLE
Temas para o próximo minicurso

### ISSUE THREAD

**Issue by ghost** [cades-ifrn/reunioes#1]
E aí, galera!

Aqui está a lista dos temas que poderão serem votados para a escolha do nosso minicurso:

- Chatbot
- Desenvolvimento de API com Flask
- Desenvolvimento de API com Node
- Projeto utilizando Electron
- Robótica
- Grafos e ArangoDB
- API Gateway - Kong
- Introdução ao Linux
- Introdução ao Git
- GraphQL com Django 
- Introdução ao Laravel
- Introdução ao Node.js
- Introdução ao Python
- Introdução a APIs RESTful (teoria + prática)

Caso vocês queiram sugerir algum tema ou retirar algum dos que já foram propostos, comentem aqui embaixo. Preciso da confirmação de vocês, pois logo abrirei uma enquete lá no facebook para os alunos de TADS votarem.

**Comment by felipemfp** [comment]
No meu ponto de vista, acho que tem opções demais. Muitos alunos de TADS não estão totalmente envolvidos com tecnologia e muitos poderão ficar perdidos nas escolhas. Acho que poderíamos filtrar um pouco essa primeira leva de minicursos.

---

PS: esse repositório é para as pautas/atas das reuniões, seria interessante criar um para discutir minicursos ou utilizar o [sobre](https://github.com/cades-ifrn/sobre) que é voltado para discussões gerais.

**Comment by luisdeol** [comment]
De momento(repito, de momento! acho válido esses posteriormente), sugiro remoção dos seguintes mini-cursos:

- Grafos e ArangoDB (bancos de dados NoSQL não são cobertos pelo curso e saltar assim em um específico acho não acho muito recomendado. Substituiria por Introdução a bancos de dados não-relacionais".
- API Gateway - Kong (de momento, ainda mais por cursos como Introdução a Node -> APIs RESTful, e o correspondente em Python e Flask, acredito que seja melhorar esperar pela conclusão desses cursos para inserir algo sobre API Gateway)
- GraphQL com Django (sem introdução a Python, nem introdução a Django, não acho interessante GraphQL com Django).

<hr/>

**Recomendação da mini-leva de cursos:**

Introdução ao Linux
Introdução a Python
Introdução a Node
Introdução a Git
Introdução a APIs RESTful
Introdução a desenvolvimento Web (podendo ser com HTML, CSS e JS ou algum framework específico baseado em Python ou Node).

_PS: Não coloquei justificativa aos outros por razões semelhantes (dependências em assuntos não cobertos por cursos nem outros mini-cursos)._

**Comment by ghost** [comment]
Gente, peço desculpas ao que já deram as suas contribuições, mas estaremos remanejando essa discussão para outra área. Acessem https://github.com/cades-ifrn/minicursos/issues.

Cya!
